#### Imports

In [14]:
import pandas as pd 
import numpy as np 
import re
import os 
from sklearn.model_selection import train_test_split

print("All impoorts successful")

All impoorts successful

In [15]:
# define file path 
RAW_DATA_PATH = "../data/raw/SQLiV3.csv"
PROCESSED_DIR = "../data/processed/sqliv3_clean.csv"
TRAIN_SPLIT_PATH = "../data/processed/train_split.csv"
TEST_SPLIT_PATH = "../data/processed/test_split.csv"

In [16]:
# load the raw SQLiv3 dataset 

df_raw = pd.read_csv(RAW_DATA_PATH, encoding='utf-8') #read dataset
df_raw.head(10)

,Sentence,Label,Unnamed: 2,Unnamed: 3
0,""" or pg_sleep ( __TIME__ ) --",1,NaN,NaN
1,create user name identified by pass123 tempora...,NaN,1,NaN
2,AND 1 = utl_inaddr.get_host_address ( ...,1,NaN,NaN
3,select * from users where id = '1' or @ @1 ...,1,NaN,NaN
4,"select * from users where id = 1 or 1#"" ( ...",1,NaN,NaN
5,select name from syscolumns where id = ...,1,NaN,NaN
6,select * from users where id = 1 +$+ or 1 =...,1,NaN,NaN
7,"1; ( load_file ( char ( 47,101,116,99,47...",1,NaN,NaN
8,select * from users where id = '1' or ||/1 ...,1,NaN,NaN
9,select * from users where id = '1' or \.<\ ...,1,NaN,NaN

In [17]:
#remove unused columns 
del df_raw['Unnamed: 2']

del df_raw['Unnamed: 3']

print("shape:", df_raw.shape)

df_raw.head()

shape: (30919, 2)

                                            Sentence Label
0                  " or pg_sleep  (  __TIME__  )  --     1
1  create user name identified by pass123 tempora...   NaN
2   AND 1  =  utl_inaddr.get_host_address   (    ...     1
3   select * from users where id  =  '1' or @ @1 ...     1
4   select * from users where id  =  1 or 1#"  ( ...     1